USE RubricaEpis
GO

INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('MARTINEZ', 'PEÑALOZA', 'MINELLY', 'minelly@hotmail.com', 1,'11111111')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('LANCHIPA', 'VALENCIA', 'ENRIQUE FELIX', 'elanchipa@hotmail.com', 1,'22222222')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('ALE', 'NIETO', 'TITO FERNANDO', 'tfale@hotmail.com', 1,'33333333')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('MENDOZA', 'YUPANQUI', 'BRUNO', 'bruno@hotmail.com', 10,'44444444')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('VALENZUELA', 'LEO', 'VIVIANA', 'viviana6@hotmail.com', 10,'55555555')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('MAMANI', 'TALA', 'EDWI', 'edwin@hotmail.com', 10,'66666666')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('CHURA', 'CHURA', 'ANTHONY', 'anthony', 10,'77777777')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('VERA', 'LOPEZ', 'EDU', 'edu@hotmail.com', 10,'88888888')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('MAMANI', 'MAMANI', 'PEDRO', 'pedro@hotmail.com', 10,'99999999')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('AROCUTIPA', 'SERRANO', 'DEIVI', 'deivi@hotmail.com', 10,'11111112')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('BELISARIO', 'BENIQUE', 'MICHAEL', 'michal@hotmail.com', 10,'11111113')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('MAMANI', 'HUANCA', 'RONALD', 'ronald@hotmail.com', 10,'11111114')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('QUISPE', 'AYACI', 'ANA', 'ana@hotmail.com', 10,'11111115')
INSERT PERSONA (ApepPer, ApemPer, NomPer, Email, CodEstamento,Dni) VALUES ('tommy', 'team', 'funny', 'tommy@team.com', 2,'11111116')
GO

INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Aplica los conocimiento y habilidades en matematicas, cientas e ingenieria para resolver problemas de ingenieria sistemas', 'Aplicacion de Ciencias', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Diseñan y conducen expermentos, analizan e interpretan datos', 'tEST', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Diseña sisteas informaticos, componentes y/o procesos para satisfacer requerimientos considerando resticciones realistas de seguridad y sostenibilidad', 'Diseño en Ingenieria', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Participa activa y efectivamente en grupos multidisciplinarios siendo capaces de liderarlos', 'Trabajo en Equipo','Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Identifica, formula y resuelve problemas de ingenieria usando las tecnicas, metodos y herramientas apropiados', 'Solucion de Problemas de Ingenieria', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Entienden sus responsabilidades profesionales, etcas, sociales y legales, y cumplen los compromisos asumidos', 'Responsabilidad etica y profesional','Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Se comunican clara y efectivamente en fora oral, escrita y grafica, interactuando con diferentes tipos de audiencias', 'Comunicacio','Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Comprende el impacto que tienen las soluciones de ingenieria en la sociedad en un contexto local y global', ' Perpectiva y Global','Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Reconocen la necesidad de mantener sus conocimientos y habilidades actualizadas de acuerdo a los avances de la ingenieria de software y sistemas de informacion y se compromete con un aprendizaje para toda la vida', 'Educacion Continua', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Conoce y analiza asuntos contemporaneos relevantes en contextos locales, nacionales y globales', 'Asuntos Contemporaneos', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Usa las tecnicas, metodos y herramientas de la ingenieria moderna necesarias para la practica de la ingenieria de software y sistemas de informacio', 'Practica de Ingenieria Moderna', 'Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Planifica y gestiona proyectos de ingenieria tomando en cuenta criterios de eficiencia y productividad', 'Gestion de Proyectos','Escuela')
INSERT resultadoaprendizaje(definicionResultadoAprendizaje, tituloResultadoAprendizaje,tipoResultadoAprendizaje) VALUES ('Desarrollo e implementa software y sistemas de informacion satisfaciendo requerimientos y aplicando metodologias, tecnicas y herramientas apropiadas', 'Desarrollo deSoftware de Implementacion deSI','Escuela')
GO

INSERT SEMESTRE (Semestre, Activo) VALUES ('2013 - EXTRAORDINARIO', '1')
INSERT SEMESTRE (Semestre, Activo) VALUES ('2013 - II', '0')
INSERT SEMESTRE (Semestre, Activo) VALUES ('2013 - I', '0')
GO

INSERT curso (CodCurso, DesCurso, CicloCurso, CursoCreditos) VALUES ('SI-968', 'AUDITORIA DE SISTEMASSS', 'IX', 4)
INSERT curso (CodCurso, DesCurso, CicloCurso, CursoCreditos) VALUES ('SI-964', 'CONTRUCCION DE SOFTWARE II', 'IX', 4)
INSERT curso (CodCurso, DesCurso, CicloCurso, CursoCreditos) VALUES ('SI-063', 'GERENCIA DE SI/TI', 'IX', 4)
INSERT curso (CodCurso, DesCurso, CicloCurso, CursoCreditos) VALUES ('SI-961', 'GESTION DE LA CONFIGURACION Y MANTENIMIENTO DE SOFTWARE', 'IX', 4)
INSERT curso (CodCurso, DesCurso, CicloCurso, CursoCreditos) VALUES ('SI-862', 'REDES Y COMUNICACION DE DATOS', 'IX', 4)
GO

INSERT carga (codper, idcurso, idsem, seccion) VALUES (1, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (4, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (5, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (6, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (7, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (8, 1, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (2, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (9, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (10, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (11, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (12, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (13, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (3, 2, 2, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (1, 2, 1, 'A')
INSERT carga (codper, idcurso, idsem, seccion) VALUES (1, 3, 1, 'A')
GO

--INSERT resultadoaprendizajedocente (idResultadoAprendizaje, idDocente) VALUES (12, 1)
--INSERT resultadoaprendizajedocente (idResultadoAprendizaje, idDocente) VALUES (13, 1)
--INSERT resultadoaprendizajedocente (idResultadoAprendizaje, idDocente) VALUES (14, 1)
--INSERT resultadoaprendizajedocente (idResultadoAprendizaje, idDocente) VALUES (15, 1)
--INSERT resultadoaprendizajedocente (idResultadoAprendizaje, idDocente) VALUES (16, 1)
--GO

INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Entiende e interpreta fenomenos naturales aplicando las leyes fundamentales que los gobierna', 1)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Aplica modelos matematicos en la solucion de problemas', 1)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Aplica conocimientos y tecnicas matematicas para analizar, modelar y simular soluciones de TI', 1)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Determina las pruebas y experimentos a realizar tomando en cuenta los estandares de calidad de requerimientos', 2)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Identifica y relaciona las variables de los sistemas de software e informacion y los mide o estima con la presicion requerida', 2)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Determina los equipos y herramientas informaticas de acuerdo a las pruebas de realizacio', 2)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Recopila informacion relevante de pruebas y experimentos similares y complementarios', 2)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Procesa y Analiza resultados usnado metodos y criterios estadisticos', 2)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('Identifica y define el problema a resolver, formula los requerimientos y los traduce en un procesos de un sistema informatico', 3)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('formula y analiza las especificaciones del proyecto de diseño considerando restricciones tanto tecnicas como economicas, sociales, y las legales, asi como las caracteristicas propias del negocio y de la organizacio', 3)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('representa y describe la solucion a traves de diagramas, y formula las especificaciones finales usando normas y estandares apropiados', 3)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('propone y evalua diversas arquitecturas y soluciones, selecciona la mas adecuada satisfaciendo los requerimientos y restricciones de seguridad', 3)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('participa como lider o mienro de un equipo de trabajo contribuyendo efectivamente en el logro de metras y resultados propuestos', 4)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('valora y considera las diferencias de opinion, respetando los acuerdos que conducen al logro de objetivos y resultados', 4)
INSERT criterioevaluacion (descripcionCriterioEvaluacion, idResultadoAprendizaje) VALUES ('se preocupa y promueve el bienestar e integracion del equipo de trabajo', 4)
GO